pool:
  name: Azure Pipelines

variables:
  # Define your variables here
  RestoreBuildProjects: '**/*.csproj'
  BuildConfiguration: 'Release'  # Example configuration, adjust as needed

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
    - job: BuildAndTestJob
      displayName: 'Build, Test, and Publish'
      steps:
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: '$(RestoreBuildProjects)'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            projects: '$(RestoreBuildProjects)'
            arguments: '--configuration $(BuildConfiguration)'
            workingDirectory: 'Backend'

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '$(Parameters.TestProjects)'
            arguments: '--configuration $(BuildConfiguration)'
            workingDirectory: 'Backend'

        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True
          
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV1@0
          inputs:
            command: 'init'
            arguments: 'terraform --version'


